import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Privacy Policy - RepostAI",
  description: "Privacy Policy for RepostAI content repurposing service.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 py-12 sm:py-20">
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to Home
      </Link>

      <article className="prose prose-neutral dark:prose-invert max-w-none">
        <h1 className="text-3xl sm:text-4xl font-bold tracking-tight">
          Privacy Policy
        </h1>
        <p className="text-muted-foreground">Last updated: April 02, 2026</p>

        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <p>
          We use Your Personal Data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold tracking-tight mt-10">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-semibold mt-8">Interpretation</h3>
        <p>
          The words whose initial letters are capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear in singular or in
          plural.
        </p>

        <h3 className="text-xl font-semibold mt-8">Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &quot;the
            Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
            this Privacy Policy) refers to RepostAI.
          </li>
          <li>
            <strong>Country</strong> refers to: China
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cell phone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> means any information that relates to
            an identified or identifiable individual. In particular, it includes
            your email address, user ID, the content you input, and the content
            generated by the Service.
          </li>
          <li>
            <strong>Service</strong> refers to the RepostAI website and its
            features.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            such as IP address, browser type, pages visited, and time spent on
            pages.
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold tracking-tight mt-10">
          Collecting and Using Your Personal Data
        </h2>

        <h3 className="text-xl font-semibold mt-8">Types of Data Collected</h3>

        <h4 className="text-lg font-medium mt-6">Personal Data</h4>
        <p>While using Our Service, We collect:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            Account information (email and user ID via Supabase Auth)
          </li>
          <li>
            Content you provide (input text or URL) and the AI-generated outputs
            (stored in your History)
          </li>
          <li>
            Usage Data (IP address, browser information, device type) for
            analytics and service improvement
          </li>
        </ul>
        <p>
          We do not collect payment information, location data, phone numbers,
          or other sensitive personal information.
        </p>

        <h4 className="text-lg font-medium mt-6">Usage Data</h4>
        <p>
          Usage Data is collected automatically when using the Service and may
          include information such as Your Device&apos;s Internet Protocol
          address, browser type, browser version, the pages of Our Service that
          You visit, the time and date of Your visit, the time spent on those
          pages, and other diagnostic data.
        </p>

        <h3 className="text-xl font-semibold mt-8">
          Use of Your Personal Data
        </h3>
        <p>We may use Your Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            To provide and maintain our Service, including to display your
            generation history
          </li>
          <li>To manage Your Account and authenticate you</li>
          <li>
            To improve and analyze the Service (using anonymized usage data)
          </li>
          <li>
            To contact You regarding important updates or security issues (if
            necessary)
          </li>
          <li>To respond to Your requests and support inquiries</li>
        </ul>

        <h3 className="text-xl font-semibold mt-8">
          Retention of Your Personal Data
        </h3>
        <p>
          We will retain Your Personal Data only for as long as necessary for
          the purposes set out in this Privacy Policy. Generation history is kept
          as long as your account is active. You may request deletion of your
          data at any time by contacting Us.
        </p>

        <h3 className="text-xl font-semibold mt-8">
          Disclosure of Your Personal Data
        </h3>
        <p>
          We do not sell Your Personal Data. We may share Your data only in the
          following cases:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            With Service Providers (such as Supabase for hosting authentication
            and database)
          </li>
          <li>
            For legal requirements or to protect the rights and safety of the
            Company and users
          </li>
          <li>
            In the event of a business transfer (merger, acquisition, etc.),
            with appropriate notice
          </li>
        </ul>

        <h3 className="text-xl font-semibold mt-8">
          Security of Your Personal Data
        </h3>
        <p>
          We use reasonable security measures to protect Your Personal Data.
          However, no method of transmission over the Internet or electronic
          storage is 100% secure.
        </p>

        <h2 className="text-2xl font-semibold tracking-tight mt-10">
          Children&apos;s Privacy
        </h2>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from children
          under 13.
        </p>

        <h2 className="text-2xl font-semibold tracking-tight mt-10">
          Changes to this Privacy Policy
        </h2>
        <p>
          We may update Our Privacy Policy from time to time. We will notify You
          of any changes by posting the new Privacy Policy on this page and
          updating the &quot;Last updated&quot; date.
        </p>

        <h2 className="text-2xl font-semibold tracking-tight mt-10">
          Contact Us
        </h2>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us:
        </p>
        <ul className="list-disc pl-6 space-y-2">
          <li>
            By email:{" "}
            <a
              href="mailto:youngyu617@gmail.com"
              className="text-primary hover:underline"
            >
              youngyu617@gmail.com
            </a>
          </li>
        </ul>
      </article>
    </div>
  );
}
